[project]
name = "nessus-organiser"
version = "0.1.0"
description = "Nessus Parser"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "Charalampos Spanias" }
]

dependencies = [
    "rich>=13.0.0",
    "PyYAML>=6.0",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"nessus_organiser.content" = ["*.yml"]

keywords = [
    "nessus",
    "vulnerability",
    "scan",
]

[project.scripts]
nessus-organiser = "nessus_organiser.cli.main:main"