"""
nessus_organiser.models.finding

Defines the Finding model used to represent organised root-cause findings 
generated by analysis modules.

Finding objects are consumed by reporting engines and should be independent from
scanner-specific concepts such as Nessus plugins and ReportItems.
"""

from dataclasses import dataclass, field


@dataclass(slots=True)
class Finding:
    """
    Represents a consultant-facing finding.

    Attributes:
        id:
            Unique finding identifier.

        title:
            Finding title.

        severity:
            Finding severity.

        instances:
            Number of underlying plugin instances.

        hosts:
            Number of affected hosts.

        services:
            Number of affected services.

        evidence:
            Human-readable evidence statements.

        references:
            Supporting references.

        affected_plugins:
            Plugin findings contributing to the
            finding.
    """

    id: str
    title: str
    category: str

    severity: str

    instances: int
    hosts: int
    services: int

    evidence: list[str] = field(default_factory=list)
    references: list[str] = field(default_factory=list)

    affected_plugins: list = field(default_factory=list)

    cvss_score: float | None = None

    commentary: str | None = None
    commentary_evidence: str | None = None
    solution: str | None = None